version: "3.9"

services:
  db:
    image: postgres:12
    command: postgres -c 'max_connections=10000'
    container_name: postgres_db_dtc
    restart: always
    volumes:
      - postgres_data_dtc:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    ports:
      - "5433:5432"
  web:
    build: .
    container_name: django_dtc
    entrypoint: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    env_file:
      - ./.env
    depends_on:
      - db
volumes:
  postgres_data_dtc: