# Generated by Django 3.2.14 on 2022-07-27 07:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Last name')),
                ('bio', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Bio')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Telegram users',
                'verbose_name_plural': 'Telegram user',
            },
        ),
    ]
