# Generated by Django 4.0.6 on 2022-07-27 11:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Last name')),
                ('bio', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Bio')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('language_code', models.CharField(max_length=3, verbose_name='Language code')),
                ('deep_link', models.CharField(blank=True, max_length=64, null=True)),
                ('is_blocked_bot', models.BooleanField(default=False, verbose_name='is blocked bot')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
